# Default image (https://hub.docker.com/_/microsoft-dotnet-core-sdk/)
image: mono:4.4.0.182

stages:
  - build
  - test



before_script:
  - dotnet --version
  - cd Project3
  - dotnet restore




# Build
build_egesz:
  stage: build
  script:
    - MONO_IOMAP=case xbuild/t:Build/p:Configuration="Debug"/p:Platform="x86" Newmazon.sln
    

# Test
test_model:
  stage: test
  script:
    - dotnet test NewmazonUnitTest

