# Default image (https://hub.docker.com/_/microsoft-dotnet-core-sdk/)
image: mono:4.4.0.182

stages:
  - build

# Build
build_egesz:
  stage: build
  script:
    - cd Project3
    - MONO_IOMAP=case xbuild/t:Build/p:Configuration="Debug"/p:Platform="x86" Newmazon.sln
    
