image: mcr.microsoft.com/dotnet/core/sdk:3.1
#image: mono:latest

stages:
  - build
  - test



before_script:
  - dotnet --version
  - cd Project3
  - dotnet restore




# Build
build_egesz:
  stage: build
  script:
    - dotnet build Model
    
build_persistence:
    stage: build
    script:
    - dotnet build Persistence

# Test
test_model:
  stage: test
  script:
    - dotnet test NewmazonUnitTest
