# Default image (https://hub.docker.com/_/microsoft-dotnet-core-sdk/)
image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test



before_script:
  - dotnet --version
  - cd Project3
  - dotnet restore

# Build
build_egesz:
  stage: build
  script:
    - dotnet build Newmazon\Model

# Test
test_model:
  stage: test
  script:
    - dotnet test NewmazonUnitTest


